---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD024:
        enabled: false
      MD013:
        enabled: false
ratings:
  paths:
  - "**.js"
exclude_paths: []
